name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '12 3 * * *'

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ 'jruby-9.3' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.81.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Build
      run: rake build
    - name: Run test
      run: rake test
    - name: Installation test
      run: gem install pkg/*.gem
