name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '12 3 * * *'

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ 'jruby-9.3' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and enable caching
    - name: Build
      run: bundle exec rake build
    - name: Run test
      run: bundle exec rake test
# Temporarily skipped until a released version of JRuby support 2.7+
#    - name: Installation test
#      run: gem install pkg/*.gem
