name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '12 3 * * *'

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ head, '3.0', '2.7' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        exclude:
        - { os: windows-latest, ruby: head }
        include:
        - { os: windows-latest, ruby: mingw }
        - { os: windows-latest, ruby: mswin }
        - { os: ubuntu-latest, ruby: 'jruby-9.3', bundle: 'bundle exec' }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and enable caching
    - name: Build
      run: ${{matrix.bundle}} rake build
    - name: Run test
      run: ${{matrix.bundle}} rake test
    - name: Installation test
      run: gem install pkg/*.gem
      if: ${{ !startsWith(matrix.ruby, 'jruby') }}
